// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnc0ptje1dT0WbsJE3tt_z7mv3wp4kNtM',
    appId: '1:831721599522:web:fff87222e08f3f9c03907b',
    messagingSenderId: '831721599522',
    projectId: 'mobile-auth-6c30c',
    authDomain: 'mobile-auth-6c30c.firebaseapp.com',
    storageBucket: 'mobile-auth-6c30c.appspot.com',
    measurementId: 'G-M8JKMVQ3SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgq38xHFGU3YeuVQqSwSGd7lgKNXC8aMw',
    appId: '1:831721599522:android:be2e47fc3964ff3f03907b',
    messagingSenderId: '831721599522',
    projectId: 'mobile-auth-6c30c',
    storageBucket: 'mobile-auth-6c30c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEajW6aavmb4MFC8bvrtKJwNb4BzooDog',
    appId: '1:831721599522:ios:91d2b8521404785703907b',
    messagingSenderId: '831721599522',
    projectId: 'mobile-auth-6c30c',
    storageBucket: 'mobile-auth-6c30c.appspot.com',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEajW6aavmb4MFC8bvrtKJwNb4BzooDog',
    appId: '1:831721599522:ios:91d2b8521404785703907b',
    messagingSenderId: '831721599522',
    projectId: 'mobile-auth-6c30c',
    storageBucket: 'mobile-auth-6c30c.appspot.com',
    iosBundleId: 'com.example.calculator',
  );
}
